apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-8eqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-8eqk
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-8eqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-8eqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-8eqk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dbcm-tenant/e2e-nodejs/nodejs-health-check-8eqk@sha256:99670ad72789a69061e568dbc20dcec0612644047f0c3de78ce6b7a7d3792114
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
