apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-health-check-8eqk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dbcm-tenant/e2e-nodejs/nodejs-health-check-8eqk@sha256:99670ad72789a69061e568dbc20dcec0612644047f0c3de78ce6b7a7d3792114
        name: my-nodejs
        resources: {}
status: {}
